os: linux
sudo: false
language: cpp
compiler:
    - gcc
    - clang

env:
    global:
        - CMAKE_PREFIX_PATH=$HOME/install

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
        packages:
            - g++-4.8
            - cmake-data
            - cmake
            - libasound2-dev

before_install:
    - mkdir $CMAKE_PREFIX_PATH
    - ( cd $HOME; git clone https://github.com/tinyalsa/tinyalsa )

install:
    - wget 'https://github.com/01org/parameter-framework/releases/download/v3.2.6/parameter-framework-3.2.6.0-Linux.tar.gz'
    - tar xf parameter-framework-3.2.6.0-Linux.tar.gz --strip-components=1 -C $CMAKE_PREFIX_PATH
    - ( cd $HOME/tinyalsa; make -j$(nproc) DOXYGEN= && make PREFIX=$CMAKE_PREFIX_PATH install )

before_script:
    - export CC=gcc-4.8 CXX=g++-4.8

script:
    - ( mkdir -p build/debug && cd build/debug &&
        cmake -DCMAKE_BUILD_TYPE=Debug $TRAVIS_BUILD_DIR && make -j$(nproc) )
    - ( mkdir build/release && cd build &&
        cmake -DCMAKE_BUILD_TYPE=Release $TRAVIS_BUILD_DIR && make -j$(nproc) )
